sudo: required

language: generic

services:
    - docker

before_install:
    - sudo /etc/init.d/postgresql stop

install:
    - sudo mv .env.example .env
    - docker-compose -f docker-compose.base.yml -f docker-compose.dev-services.yml pull
    - docker-compose -f docker-compose.base.yml -f docker-compose.dev-services.yml build

script:
    - docker-compose -f docker-compose.base.yml -f docker-compose.dev-services.yml up -d
    - sleep 60
    - docker ps -a
    - docker images
